<?php

namespace Database\Seeders;

use App\Models\Indicator\IndicatorType as IndicatorIndicatorType;
use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class ProfessionNossaSeguros extends Seeder
{
    public function run()
    {
           /**IndicatorType */
           $IndicatorType = [
            ["description" => "Contabilistas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Contabilista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Auditores", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Revisores oficiais de contas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Consultores fiscais", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Notários", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Advogados", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Solicitadores", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Outros profissionais independentes", "risk" => "Baixo", "score" => 1],
            ["description" => "Funcionário bancário", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Agente de seguros", "risk" => "Baixo", "score" => 1],
            ["description" => "Corretor de seguros", "risk" => "Baixo", "score" => 1],
            ["description" => "Intermediário de crédito", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Corretor de valores", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Empregado de mesa", "risk" => "Baixo", "score" => 1],
            ["description" => "Caixeiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Caixeiro-viajante", "risk" => "Baixo", "score" => 1],
            ["description" => "Industrial", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Empresário", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Comerciante", "risk" => "Baixo", "score" => 1],
            ["description" => "Padre", "risk" => "Baixo", "score" => 1],
            ["description" => "Pastor", "risk" => "Baixo", "score" => 1],
            ["description" => "Bispo", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cardeal", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Papa", "risk" => "Alto", "score" => 3],
            ["description" => "Missionário", "risk" => "Baixo", "score" => 1],
            ["description" => "Militar", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Polícia", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Juiz", "risk" => "Alto", "score" => 3],
            ["description" => "Deputado", "risk" => "Alto", "score" => 3],
            ["description" => "Ministro", "risk" => "Alto", "score" => 3],
            ["description" => "Primeiro-ministro", "risk" => "Alto", "score" => 3],
            ["description" => "Presidente da República", "risk" => "Alto", "score" => 3],
            ["description" => "Governador", "risk" => "Alto", "score" => 3],
            ["description" => "Presidente da Câmara Municipal", "risk" => "Alto", "score" => 3],
            ["description" => "Vereador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Funcionário público", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Professor", "risk" => "Baixo", "score" => 1],
            ["description" => "Médico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Enfermeiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Farmacêutico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Engenheiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Arquitecto", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Jornalista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Estudante", "risk" => "Baixo", "score" => 1],
            ["description" => "Desempregado", "risk" => "Baixo", "score" => 1],
            ["description" => "Reformado", "risk" => "Baixo", "score" => 1],
            ["description" => "Doméstica", "risk" => "Baixo", "score" => 1],
            ["description" => "Agricultor", "risk" => "Baixo", "score" => 1],
            ["description" => "Pescador", "risk" => "Baixo", "score" => 1],
            ["description" => "Operário", "risk" => "Baixo", "score" => 1],
            ["description" => "Operários", "risk" => "Baixo", "score" => 1],
            ["description" => "Motorista", "risk" => "Baixo", "score" => 1],
            ["description" => "Taxista", "risk" => "Baixo", "score" => 1],
            ["description" => "Bombeiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Atleta", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cantor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Artista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Actor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Actriz", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Modelo", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Diplomata", "risk" => "Alto", "score" => 3],
            ["description" => "Embaixador", "risk" => "Alto", "score" => "3"],
            ["description" => "Cônsul", "risk" => "Alto", "score" => 3],
            ["description" => "Agente imobiliário", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Construtor civil", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Electricistas", "risk" => "Baixo", "score" => 1],
            ["description" => "Montadores", "risk" => "Baixo", "score" => 1],
            ["description" => "Electricistas", "risk" => "Baixo", "score" => 1],
            ["description" => "Montadores", "risk" => "Baixo", "score" => 1],
            ["description" => "Padeiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Carpinteiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Serralheiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Pedreiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Pintor", "risk" => "Baixo", "score" => 1],
            ["description" => "Jardineiro", "risk" => "Baixo", "score" => 1],
            ["description" => "Vendedor ambulante", "risk" => "Baixo", "score" => 1],
            ["description" => "Feirante", "risk" => "Baixo", "score" => 1],
            ["description" => "MANICURE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "VINAGREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PASSAMANARIEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LUSTRADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PINTOR AUTOMÓVEL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRAVISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SERVIÇOS DE HOTELARIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESPECIALISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DE CIMENTOS E SEUS PRODUTOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FERRADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AJUDANTE DE FARMÁCIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL SUPERIOR NA REFORMA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACERTADOR OU ACERTADEIRA DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GUARDA DE HERDADES OU FLORESTAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TELEGRAFISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CHEFE DE DEPARTAMENTO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SERRADOR DE FERRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COLCHOEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MAÇARIQUEIRO (VIDRARIA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRIMINOLOGA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PONTEADOR DE CALÇADO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONTABILISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PRODUTOR ÁUDIO VISUAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAPADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MECÂNICO DENTISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PASTELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COVEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GERENTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BRONZEADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MONTADOR DE ANDAMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RETROSEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AGENTE DE CAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORJADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADEIRA (CHICÓRIA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "APARELHADOR DE PEDRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOTORISTA MARÍTIMO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "NAVEGAÇÃO E CONTROLE MARÍTIMO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ARREEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE DELIGÊNCIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMBALADOR DE ESPELHOS OU LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "APANHADOR DE PEIXE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRAVADOR (DE JÓIAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CATOQUEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FIVELEIRO DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LOGÍSTICA E ARMAZÉM", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CANASTREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FAXINA (CORTIÇAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TRAÇADOR DE LOUSA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOTORISTA TERRESTRE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DESENFORNADOR (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DENTISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRIADO (CRIADA) DE SERVIR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LOGÍSTICO DE ARMAZÉM", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMBALADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCOLHEDOR DE VIDROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GRANEADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "NAVEGADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PICADOR DE MÓS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CERÂMICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PREGADOR DE LANIFÍCIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FUNCIONÁRIO (A) PÚBLICO, OFICIAL ESPECIALISTA DE FORMAÇÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PINTOR DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIOS METALÚRGICOS DE MÁQUINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DE TESOURAS MECÂNICAS (CONSERVAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LADRILHADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DESENROLADOR (FÓSFOROS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCARREGADO GERAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE CONSERVADOR DE 1º CLASSE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AJUNTADOR (AJUNTADEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MESTRE FLORESTAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BIBLIOTECÁRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DE OPERAÇÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCRIVÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SELECCIONADORES DE PELES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BOIEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ASSISTENTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TELE-MARKETING", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ATENDIDORA COMERCIAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OLEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAVADEIRA DE BORDADOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ULTIMADORES DE FIOS E TECIDOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GRAVADOR DE IMPRENSA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PREPARADOR DE LACTICÍNIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ZOTECNISTA REFORMADA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CINZELADOR (CINZELADORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTENÓGRAFO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GARAGISTA DE AUTOMÓVEIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FIEL DE BALANÇA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GARSON", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CILINDRADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LINGUISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ECONOMISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RECOVEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CEREEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARPINTEIRO CIVIL OU DE MINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BOBINADEIRA DE LANIFÍCIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PRESIDENTE DA COMISSÃO EXECUTIVA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PEDIATRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTOFADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "JORNALEIRO (JORNALEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GASPEADEIRA DE SAPATOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENFERMEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LINOTIVISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PREPARADOR DE LABORATÓRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PESCADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ABEGÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOLICEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE OPERAÇÕES AEROPORTUÁREA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENGENHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE OPERAÇÃO DE VOO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCOMBREIRO (MINAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AVISADOR DE CENA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADOR MECÂNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ALQUILADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BRITADOR DE PEDRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAGAREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACABADOR DE TECELAGEM OU DE CORREIAS DE TRANSMISSÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RADIALISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACABADOR DE CUTELARIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EDITOR DE IMAGEM", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TAQUEIROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PICHELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENGOMADEIRO (ENGOMADEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TEMPERADOR DE LIMAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CABINISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DO FABRICO DE EMBALAGENS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ARMADOR DE VITRAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ROSSADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GEÓLOGO DE PETRÓLEO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "VARREDOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GANHÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MONTADOR DE TIRA (CONSERVAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CIGARREIRO (CIGARREIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRIADO DE HOTEL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE NOTÁRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CERZIDOR (CERZIDORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FÍSICO E QUÍMICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCARTADEIRA DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "METALOMECÂNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AMOLADOR (AMOLADORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EXPEDIDOR DE MERCADORIAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIOS DE PLÁSTICOS ARTIFICIAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PELADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "APANHADOR DE FRUTOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ANGARIADOR DE SEGUROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RESPONSÁVEL DE RECURSOS HUMANOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PROJETISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PANTELEIRO (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AGUÇADOR DE FERRAMENTAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GRAVADOR DE VIDRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOVIMENTADOR DE PRODUTOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CANTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TAPETES (OPERÁRIOS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CERAMISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SARRAFIADOR DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCAIOLADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PENTEEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ADJUNTA PRINCIPAL DO CONSERVADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "POLIDOR DE METAIS, DE GALALITE OU DE PEDRAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCAIXILHADEIRO DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LOUSEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ATACADOR DE PEDREIRAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DE CONSTRUÇÃO CIVIL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESPECIALISTA DE SERVIÇOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSPECTOR DO TRABALHO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SAPATEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DOCEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OURIVES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCARREGADO DE BOMBA DE GASOLINA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LEITEIRO (LEITEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "METEDEIRA DE FIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "VIDERACEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INVESTIGADOR CRIMINAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERADOR CINEMATOGRÁFICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GARIMPEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTRIADOR DE CILINDROS (MOAGEM)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DO TRATAMENTO MINÉRIO E DO APARELHAMENTO DE PEDRAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AGENTE SÉNIOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MALHADOR METALÚRGICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MÚSICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONTÍNUO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GESTOR(A)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE JUSTIÇA DE 3 CLASSE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LEITOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INTÉRPRETE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MAGAREFE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GUARDA-LIVROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PINCELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCOVEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "JARDINEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENFORNADOR (VIDRACEIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PESADOR DE MOAGEM", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DIRECTOR COMERCIAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENTALHADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCARREGADOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMPREGADO DE COMÉRCIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ALISADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "NIQUELADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REPORTER DE IMAGEM", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BATEDOR DE SOLA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PORTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO AGRÍCOLA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MINIATURISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SAFREIROS (MINAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAIXOTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADOR (CORTADEIRA) DE GALALITE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARPINTEIRO DE CENA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ROLHISTA (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCOLTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ORTOPEDISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSPECTOR MUNICIPAL DE SAÚDE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARPINTEIRO DE MOLDES, CAIXOTES OU CARROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAVANDEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MEDIDOR ORÇAMENTISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GUARDA-FIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ARREMATADEIRA DE CABEDAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LUBRIFICADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO DO FABRICO DE PRODUTOS QUÍMICOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SACERDOTE / PADRE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PALMILHADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "JURISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PASSADOR DE CORTIÇAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MONTADOR DE CENA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFERENDE DE CARGA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOLEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SUBESCRITOR DE SEGUROS CORPORATIVO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CHAPEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ATENDENTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CANALIZADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GEO-FÍSICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PROGRAMADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "APLAINADOR DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BARBEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FOGUEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCARREGADO DE TRABALHO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESMALTADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PERFEITO DE ESTUDO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "NÃO ESPECIFICADA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARPINTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MADRE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REBORDADOR VIDREIRO OU CERÂMICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MANUTENTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAIXA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PRECEPTOR (PRECEPTORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FRENTE LOJAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RETOCADOR DE MÓVEIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "VENDEDOR AMBULANTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FREZADOR (FREZADEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TIPÓGRAFO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GUILHOCHADEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENGARRAFADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESPARTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PREPARADOR DE PASTA DE CERÂMICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMPACOTADOR DE MASSAS ALIMENTÍCIAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMISSOR DE 1ºCLASSE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SERRALHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ADMINISTRADOR EMPRESAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESPECIALISTA DE EMIGRAÇÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAIXEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORMADOR DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSPECTOR DE TRANSPORTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FUNCIONÁRIO (A) PÚBLICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARREGADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "JOALHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MEDIADOR SEGUROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BATEDEIRA (CONSERVAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTANHADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MINISTÉRIO DA SAÚDE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GOVERNANTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GÁSTRONÓMICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ASCENSORISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SOQUEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CHAPELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CESTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AFINADOR DE MÁQUINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTIVADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COMPOSITOR (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DESCARNADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TIRADOR DE CORTIÇA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FERRAMENTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MASSAGISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PINTOR DE OBRAS DE ARTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MECÂNICO MÁQUINAS DE ESCREVER", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Mestre de Vapores", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cravador (Manual ou Mecânico)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Estatístico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Mediador Propriedades", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Guarda Rural", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Corretor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Investigador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Banheiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Projetista Reformada", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Chanfrador de Correias de Transmissão", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Sapador de Disminagem", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Rachador de Lenha", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Guilhotineiro Metalúrgico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Conserveiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Tabaqueiro (Tabaqueira)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Tubista (Minas)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Repórter", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Mergulhador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Gravador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Motorista de Fábrica", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Droguista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Funcionário (a) dos Caminho de Ferro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Grosador de Curtumes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Balanceiro (Chicória)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Especialista de Elvação de Gás", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Avaliador de Diamantes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Moço de Recados", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Empregado de Ascensor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cartógrafo", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Manipulador de Massas Alimentícias", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Moço Rural", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cantoneiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Activista Social para Área de Saúde", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Mecânico Automóveis", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Gravador e Prensador de Curtumes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cortador de Peles ou de Sola", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Aparelhador de Madeira", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Responsável de Compra", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Relações Público", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Colhereiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Inspector Ferroviário", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Inspector Superior Segunda Classe", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Criado de Café", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Oficial Judiciario", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Carteador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Manipulador de Tabaco", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cardeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Medidor de Curtumes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Psicólogo", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Saboeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Pontogravador (Vidreiro)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Montador de Máquinas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Modista de Chapéus", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Marinheiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Traçador de Cortiça", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Funileiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Debuxador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Físico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Lubrificador de Automóveis", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Ferreiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Pregoeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Provador de Vinhos", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Coordenador das Comunicações", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "HSS Supervisor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Licoreiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Tratador de Peixe", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Descarregador de Mar e Terra", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Criado de Lavoura", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Foscador de Vidros", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cromador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Alpargateiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Oficial de Protocolo de Estado", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Adegueiro (Encarregado de Adega)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Copeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Rebardador de Botões", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Recortadeira de Bordados", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Sineiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Barqueiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Acabador de Cerâmica", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Conservadora", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Guardador de Feras", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cervejeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Relojoeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Moço de Armazém", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Apanificador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Fragateiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Preparador de Bebidas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Tratador de Gado", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Azulejador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Curtidor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cortador Carnes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Ensacador (Moagem)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Carroceiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Agulheiro (Carros Eléctricos)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Decorador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Copeira", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Vaqueiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Notário", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Empregado de Escritório", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Maquilhadora", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cozedor de Pintura a Fogo (Vidreiro)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Polidor de Madeira ou de Vidro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Padeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Encarregado de Manutenção dos Equipamentos Pesados", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Operários de Moagem e Descasque de Cereais", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Oculista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Serrador Mecânico de Madeira ou de Lousas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Pisceiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Polideira de Botões", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Redeiro de Pesca", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Arameiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Guilhotineiro (Fósforos)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Gerenciador Comercial", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Recebedor Ferroviário", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Aprestador de Curtumes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Organizadora Eventos", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Ampolas Vidro (Marcadoras, Limpadores, Cortadores, Espalhadores)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SAÚDE PÚBLICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "IMEDIATO DA MARINHA MERCANTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FURADEIRA DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DESBARRADEIRA (LANIFÍCIOS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TOSQUIADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PROFISSIONAL MARKTING", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ARQUISTA (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAMINADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DOBRADORA (IMPRENSA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORRECTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAVADOR DE CHICÓRIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "APONTADOR (APONTADORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTATÍSTICO HOSPITALAR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CUTILEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PILOTO AVIADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BISCATEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENXOFRADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MINEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMPILHADOR (EMPILHADEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BATE-CHAPA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONSERTADEIRA DE BORDADOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PENEIREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSTRUTOR PROCESSUAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO QUALIFICADO DE PRIMEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRAVADEIRA DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FIGURANTE DE CENA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTILISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESTUDANTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PARAFUSEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BABÁ", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PROVISTA (IMPRENSA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BILHETEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESPECIALISTA DE PRIMEIRA CLASSE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ABRIDEIRA DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AGENTE VIAGENS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TEMPERADOR DE VIDROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CABO DE BANDA OU DE VARANDA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PEIXEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COSTUREIRA DE ESTOFADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TÉCNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO NA PREPARAÇÃO DA LÃ", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOLEIRAO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DESCARREGADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "JUNTADEIRO (JUNTADEIRA) DE LANIFÍCIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSPECTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RACHADOR DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ZINCÓGRAFO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LIVREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTINEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MECÂNICO CADEIRAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CHEFE DE ESTAÇÃO (FERROVIÁRIO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENFIADEIRA DE AMPOLAS DE VIDRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OFICIAL DE CONSERVADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COLHEDOR (VIDRACEIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CALISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTICEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RESINEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAMAREIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REVISOR (CARROS DE TRANSPORTE COLECTIVO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADOR (CORTADEIRA) DE LOUSAS, PEDRAS OU CERÂMICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DISTRIBUIDOR (RESINAS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MONTADOR DE CERÂMICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MODELO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MACHEIRO DE FUNDIÇÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAIXEIRO DE PRAÇA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REFRIGERANTES (MANIPULADOR)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RELEVISTA (IMPRENSA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ELECTRICISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAPATAZ (AGRÍCOLA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MANICURA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FUNCIONÁRIO (A) ADMINISTRATIVO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TOSADOR DE LANIFÍCIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADOR DE TACOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCRITURÁRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARPINTEIRO DE ESTRUTURA DE MÁQUINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONTA PRÓPRIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "QUEIMADEIRA (VIDREIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO METALÚRGICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DEPART. DE TRANSPORTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CRIVEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GEÓLOGO FISCAL DE OBRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RESPONSÁVEL DE OPERAÇÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DOMÉSTICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MARNOTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SACHADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PODADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "RECORTADOR DE CORTIÇA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAVALEIRO TAUROMÁQUICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSPECTOR MARÍTIMO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACABADOR DE SAPATARIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PROFISSIONAL DE SAÚDE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "HORTELÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MARÍTIMO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MANEQUIM ARTÍSTICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ALVANÉU", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MARKETING DIGITAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MANUFACTOR DE FLORES ARTIFICIAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCOLHEDOR DE MINÉRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SERRADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONFEITEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TORRADOR DE CAFÉ E OUTROS PRODUTOS VEGETAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GALVANIZADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "POLITÓLOGO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORRAGEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BORDADOR (BORDADORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REPOSITORA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "APLICADOR REVESTIMENTO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LIMPADOR DE VIAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "QUÍMICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BALCONISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ARQUITECTO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MARCADOR METALÚRGICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LINGADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIO FABRIL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LOCUTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AMBIENTALISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Agente Técnico de Engenharia", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Apartador (Apartadeira) de Lanifícios", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Arrais", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Fiel Transportador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Casquilheiro ou Casqueiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Panificador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Comerciante", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Limpador de Pedras", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Consultor(a)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Oficial", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Secretário (a)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Rendeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Fotógrafo", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Varejador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Biselador de Vidros", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Operários de Borracha e Pneus", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Responsável Logístico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Sirgueiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Armador e Decorador", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Tachinha ou Tachista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Tecedeira", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Pastor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Pregoeiro Mecânico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cartazeiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Espigador Metalúrgico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Condutor de Carros Eléctricos ou de Comboios", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Acabador e Afagador de Lousa", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cozedor e Cortador de Ampolas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Feirante", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Martelador de Peles", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Raspador de Cortiças", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Director Técnico", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Limpador de Árvores", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Levantadeira de Conservas", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Animador Digital", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Preparador de Fios", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Empalhador (Empalhadeira)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Alfaiate", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Comissário de Bordo", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Guardador de Gado", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Funcionário (a) Público Feche de Departamento", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Empregado de Teatro ou Casa de Espectáculos", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Escalador de Peixe", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Carcereiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Seguros", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Apartador ou Classificador de Curtumes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Limpador de Curtumes", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Piscicultor", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Vergador de Fios", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Cabeleireiro (Cabeleireira)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Angariador de Publicidade", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Geólogo (a)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Torneiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Percheiro (Lanifícios)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Inspector de Operações", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Ferrageiro", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Facetador de Vidros", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Recursos Humanos", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Progestista", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Reformado", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Carvoeiro (no Fabrico)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "Emissora de Primeira Classe", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CARREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORNEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BRANQUEADOR MECÂNICO DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PILOTO DA MARINHA MERCANTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACABADOR DE VIDRO E DE VIDRAÇAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENGRAXADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AMA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MONDADEIRA (MONDADOR)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LIMADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LOGÍSTICA PATRIMÓNIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CANELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "OPERÁRIA QUALIFICADA DE 2º CLASSE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SOTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GASPEADOR DE TANOARIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAVADOR DE LANIFÍCIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AMARRADEIRA DE FIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCERADOR (ENCERADORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TONELEIRO OU BALSEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GUARDA-FREIO (ELÉCTRICOS OU COMBOIOS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BATANEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CABELEIREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACTOR DE TEATRO OU DE CINEMA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PAQUETE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FIEL DE ARMAZÉM OU DE CENA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONSERVADOR ADJUNTO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CASTELEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COLADOR (LANIFÍCIOS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TAMANQUEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORNALISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "POCEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAPISEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "EMBAIXADORA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LAVADOR DE VIDROS E GARRAFAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MECÂNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ARRUMADOR (ARRUMADORA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MARTELADOR DE PEDRAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COMPOSITOR (IMPRENSA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORTADOR DE BANCADA (ESPELHOS E VIDRAÇA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TRANSPORTADOR (IMPRENSA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CAIXEIRO DE BANCO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DACTILÓGRAFO (DACTILÓGRAFA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GALOCHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ALCATROADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PINTOR DE CONSTRUÇÃO CIVIL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REPARADOR DE MÁQUINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ZINCADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FICHEIRO DE BANCA DE JOGO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FILME MAKER", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "AMACIADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ENCARREGADO DE TOUCADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CÓMICO TAURINO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "URDIDEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CORISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LIXADEIRO DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSTRUTOR DE NATAÇAO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "INSPECTOR DE CERTIFICAÇÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "DAMA DE COMPANHIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "MOAGEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORMISTA DE CERÂMICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESCOLHEDEIRA DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LUVEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BAR-MAN / DJ", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PULVERIZADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FOTÓGRAFO CROMISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "BALSAMEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "GASOGENISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ESMERILADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CEIFEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PICADOR DE LIMAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COSTUREIRO (COSTUREIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "COCHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PSICÓLOGO CLÍNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PEGADOR DE FIOS, DE PENTEADO OU DE CARDADO (LANIFÍCIOS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "CONFERENTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "ACTIVISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "FORRADORA DE FIOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "REPARADOR DE CARRIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "SACERDOTE CATÓLICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "PAUZEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "TEAM LIDER", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
            ["description" => "LITOGRAFO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "DISTRIBUIDOR DE PÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OPERÁRIO DE RANPA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PUXADOR DE PONTO (METALÚRGICO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LOUCEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "INSPECTOR (A)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RASPADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TESOUREIRO (DE ESCRITÓRIO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "COLOCADOR DE VITRAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LINGOTEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "AMASSADOR (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SUPERINTENDENTE INTELIGÊNCIA DA CLÍNICA GIRASSOL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "GUARDA DE FÁBRICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENVERNIZADOR OU ENVERNIZADEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENSAIADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "REGENTE FLORESTAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "APANHADOR DE MOLIÇOS E DE ALGAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ACABADEIRA DE BORDADOS OU TAPETES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PAGADOR DE MESA DE JOGO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESPECIALISTA DE TRANSPORTES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "VIDREIRO (ENFIADEIRA, ESPELHADOR, MONTADOR)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SOLDADOR A AUTOGÉNEO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SAQUEIRO (MOAGEM)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PROJECCIONISTA DE CENA OU DE CINEMA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CROMISTA GRAVADOR OU RETOCADOR (IMPRENSA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TRACTORISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OSTREICULTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESPARTILHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CAÇADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SUB DIRECTORA PEDAGÓGICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "BOTOEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENCAIXOTADOR (VIDRACEIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FECHADEIRA DE BOTÕES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "DANÇARINO (DANÇARINA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RESTAURAÇÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "COZINHEIRO (COZINHEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SEGEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LIMPA-CHAMINÉS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SERVIÇAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "AGENCIÁRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TECNICO DE CONTAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PLANIFICADOR DE NAVIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENCARREGADO DE OBRAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CAPACHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LATOEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "EMPRESÁRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OPERÁRIO ESPECIALIZADO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "BOLETINEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CONTRA-REGRA (TEATRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESTAMPADOR (ESTAMPADEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RECEBEDOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MOÇO DE FRETES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FINGIDOR (CONSTRUÇÃO CIVIL)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESCULTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CHEFE DE SALGA DE BACALHAU", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FIANDEIRO (FIANDEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MARCENEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "VARREDORA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESCOLHEDOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESPELHADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "COMPRADOR SÉNIOR DA LOGÍSTICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MAQUINISTA EM OFICINAS, FÁBRICAS OU MINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESTAFETA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OPERADOR (A)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CHEGADOR METALÚRGICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESTEREOTIPADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CONCESSIONÁRIO DA SONANGOL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PSICÓLOGA CLÍNICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MÉDICO(A)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "INSPECTOR DE MATERIAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CONDUTOR DE MÁQUINAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CAMISEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "HOTEREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESCOLHEDOR DE PEIXE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MALHÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "BRUNIDOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "DESINFECTADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FUNDIDOR-MOLDADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PREGADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MEXEDEIRA DE MASSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "VIGILANTE DE ESTUDOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PICADEIRA DE LOUSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "DEMOLHADOR DE TECELAGEM", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PRENSEIRO OU PRENSADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "EMPREITEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MERCEEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "QUINQUILHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CREOSOTADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RECACHOTADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FACTOR FERROVIÁRIO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PREPARADOR DE MASSA DE PAPEL E CARTÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CAVADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MAQUINISTA DE CAMINHOS DE FERRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FERREIRO MECÂNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PIROTÉCNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PROMOTOR DE SAÚDE PÚBLICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "COBRADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENFARDADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ADMINISTRADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OFICIAL DE MARINHA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "EXPEDITOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TRIPEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CARNICEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MOÇO DE FRAGATA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CRIADO DE MESA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CALDEIREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "GUARDA DE VIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PICADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "AFINADOR DE PIANOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "AGRIMENSOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MESTRE DE REDES DE PESCA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CHOCOLATEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CAIXEIRO VIAJANTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESTENDEDEIRA DE MASSAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ROÇADEIRA (VIDREIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "GUIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "VIDRACEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TRABALHADOR RURAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OFICIAL GENERAL NA REFORMA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENCARREGADO DE MANUTENÇÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "VASSOUREIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OPR. DE PROD. DE PETRÓLEO E GÁS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RESPONSÁVEL DE TRANSPORTE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CARVOEIRO (NA VENDA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ATIÇADOR (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SOCIAL-MÉDIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CALCETEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PSICÓLOGA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FARMACÊUTICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ATARRACHADOR MECÂNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "EMPILHADOR DE CORTIÇAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LAVADOR DE AUTOMÓVEIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "REPOSITOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TELHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MARMORISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TROLHA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "BIOQUÍMICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ADVOGADO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "BANDARILHEIRO TAUROMÁQUICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TECNICO ELECTRONICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CONSERTADOR DE LOUÇA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LASHING", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FABRICANTE DE FERMENTO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TUPIJADEIRA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RESPONSÁVEL DE ALOJAMENTO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "INDUSTRIAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESPALMADOR MECÂNICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LIDER 1 DE PROCESSOS INDUSTRIAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PERFUMISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CAMPINO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "HORTICULTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "COSTUREIRA (DOBRADORA) DE IMPRENSA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "FOTOGRAVADOR CROMISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "DESENHADOR-DECORADOR (ESMALTAGEM)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CASEIRO (CASEIRA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PRODUTOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "AGULHEIRO (FERROVIÁRIO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PLANEADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESPECIALISTA ADUANEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ENROLADOR OU MONTADOR DE ACESSÓRIOS (CURTUMES)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MAQUINISTA NAVAL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "BILHETEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "POLIDOR DE METAIS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PRESTADOR DE SERVIÇOS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "DESCASCADOR DE ARROZ", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CENÓGRAFO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "TAQUÍGRAFO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "POTEIRO (VIDREIRO)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESTUCADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESTUFEIRO (CHICÓRIA)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CORDOEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OPERÁRIOS DE MALHAS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ACABADOR DE PAPEL E CARTÃO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "OPERÁRIO DA INDÚSTRIA TÊXTIL", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CARDADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LOGÍSTICO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SALINEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ABEGÃO (DE CARROS)", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESCORREDOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "RACHADOR DE GALALITE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ROLHEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "SELEIROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "PENSIONISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "VINHATEIRO", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "LIXADOR DE CURTUMES", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MONTADOR-ELECTRICISTA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "MANIPULADOR DE FÓSFOROS", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "CALAFATE", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "ESPECIALISTA DE LOGÍSTICA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "QUADRADOR", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ["description" => "INSPECTOR DE INDUSTRIA", "risk" => "Médio",  'score' => 2, 'indicator_id' => 5],
        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorIndicatorType::where('description', $value['description'])->exists()) {
                IndicatorIndicatorType::create($value);
            }
        }

    }
}
