<?php

namespace Database\Seeders;

use App\Models\Indicator\IndicatorType as IndicatorIndicatorType;
use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class TypeActivitySeed extends Seeder
{
    public function run()
    {
           /**IndicatorType */
           $IndicatorType = [

                      /** Tipo de Actividade Principal Colectiva */
                      ['description' => 'Fab.sabões e Deterg., prod. Limp.e polim', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.perfumes, cosméticos e prod. higiene', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. explosivos e artigos  pirotecnia', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. outros prod. químicos diversos', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. fibras sintéticas ou artificiais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'FAB.PROD. FARMA.BASE PREP FARMACÊUTICAS', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Consd.A Asilnor-Socied.Gráfica Limitada', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. pneus e câmaras-ar', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Reconstrução pneus', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. prod. borracha, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.chapas, folhas, tubos e perfis plást', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. embalagens plástico', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. artigos plástico, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. vidro e artigos  vidro', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. prod. cerâmicos refractários', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.azulejos, ladri., mosai. placas cerâ', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.tijol,telhas out. prod.barro p/Const', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.out. prod.porcel.cerâm n/refractário', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. cimento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. cal e gesso', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. betão Pronto, (exc.bloco)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. prod. fibrocimento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. blocos cimento p/construção', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. outros prod. betão, gesso cimento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Serrag,corte acab rocha orna pedras Cons', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. outros prod minerais n/metálicos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => 'Ind. metalúrgicas base do ferro e aço', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Obten. primeira transf. metais preciosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Obtenção e primeira transformação zinco', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Obten.prim. transf.out.metais n/ferrosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fundição ferro fundido e aço', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fundição metais não ferrosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. estruturas construções metálicas', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. portas, janel. Elem.simil. em metal', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.reserv,recip,radi.met.p/aque.central', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.gerad vapor(exc.cal. p/aquec.central', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. armas e munições', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.prod.forjados,estam.lami.;metal pós', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Trat.Revest. metais;Activ.mecânica geral', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. cutelaria', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. fechaduras, dobradiças ferragens', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. ferramentas metálicos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. embalagens metálicas', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.prod.aram,reb,paraf.,mola corr.metál', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. outros prod.s metálicos.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. componentes e  placas, electrónicos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.computadores equipamento periférico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. equipamentos comunicação', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.recep.rádio tv bens consumo similare', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.inst.aparelhos medida,naveg out.fins', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. relógios e material relojoaria', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.equip.radiação, elect. Electroterapê', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. material e equipamento óptico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.suportes infor. magnéticos e ópticos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. motores, geradores,transf. eléctric', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.mat. distrib.controlo p/inst.eléctri', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. acumuladores e pilhas eléctricas', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.fios e cabos isolados e seus acess.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.lâmpadas eléctr. e outro mat. Ilumi.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. electrodomésticos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.aparelhos n/eléctricos p/uso domést', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. outro equipamento eléctrico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.motores turbinas, exc.mot.p/aeronave', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.equip.hidráulico pneum,compr.,válvul', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.rolam.,engrena. out. órgãos transm', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. fornos e queimadores', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.equipamento elevação e movimentação', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.máq.equip.escr,exc compt.equip.perif', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.máquinas-ferrament portáteis c/motor', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. outras máquinas  uso geral', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.Máq.Tract.p/agricult.pecuária silvic', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],

                      ['description' => 'Fab.outras máq.-ferram., excepto portát.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. máquinas para a metalurgia', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.máquinas p/indú. extr. e p/Const.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.máq p/ind aliment,bebidas e tabaco', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.máqui p/indú. têxt.,do vest.e couro', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.outras máquinas equip.p/uso específi', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. veículos automóveis', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.carroçarias, reboques e semi-reboque', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.comp.acess.p/veíc autom. seus motore', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Const.embarcações,excepto recreio e desp', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Const. embarcações  recreio e sporto', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.mat. circulante p/caminhos-de-ferro', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.aeronaves,veículos esp.equip.relac.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. veículos militares combate', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. motociclos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.bicicletas e veículos p/defic.físico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. outro equipamento transporte, n.e', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. mobiliário maira', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. mobiliário metálico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. colchões', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. mobiliário n.e.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.Joalh.,ouriv.artig sim.;cunhage moed', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. bijutarias', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. instrumentos musicais', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab  artigos desporto', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. jogos e brinquedos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab.instr. e material médico-cirúrgico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. vassouras, escovas e pincéis', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. canetas, lápis e similares', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Fab. caixões mortuários em maira', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Outras indústrias transformadoras div.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Rep.manu prod. metál,exc Rep.máq e equip', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Rep.e manutenção máquinas e equipamentos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Rep. manut. equip. electrónico e óptico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Rep. e manutenção equipamento eléctrico', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Rep.manut.equip.Transp.,excep veíc.auto', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Rep. e manutenção outro equipamento', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Instal. máq. e equipamentos industriais', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Produção electricida', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Transporte electricida', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Distribuição e comércio electricida', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Prod.gás; distrib.Comb.gasosos p/conduta', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Prod.distr.vap,ág.qte fri,ar frio p/cond', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Produção gelo', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'CAPTAÇÃO,TRATAMENTO E DISTRIBUIÇÃO ÁGUA', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'RECOLHA, DREN. E TRAT. ÁGUAS RESIDUAIS', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Recolha resíduos não perigosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Recolha resíduos perigosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Trat. e eliminação resíduos n. perigosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Trat. e eliminação resíduos perigosos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Valorização sucatas e resíduos metálicos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Valorização resíduos não metálicos', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Descontaminação e atividades similares', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Distribuição de Eletricidade', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Promoção imobiliária', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Const. edifícios (resi. e n/residenc.)', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Const.auto-estrada,túneis,ponte,via férr', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Const.redes Transp.água,telec.outras red', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Const. outras obras engenharia civil', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Demolição e Prep. dos locais para Const.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Instalação eléctrica', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Instalação canalizações e climatização', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Outras instalações em construções', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Montagem trab. carpintaria e caixilharia', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Estucagem,revestimento pavimento e pares', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Outras atividades de acabamento', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => '(031094) Actividades de acabamento mobiliário', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => '(014133) Actividades de acabamento de artigos de vestuário', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Aluguer equip. Constr. e dem., c/operador', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Outras obras especializadas Const., n.e.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Comércio veículos automóveis', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Manutenção e Rep. veículos automóveis', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.peças e acess p/veículos automóveis', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Comercio G. P. Acess. Veiculo Automaveis', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com. ret. pecas e acess p/veiculos autom', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.,manut.Rep.Moto.,suas peças e acess', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Manut. e Rep. motociclos, peças e acessó', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agent.Com.p/grosso mat.primas agríc.têxt', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agent.Com.p/grosso prod.quím.p/ind, máq', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agent.Com p/grosso maira, mat.Const.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agentes Com. prod.alim.,bebidas e tabaco', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agent. Com. por grosso misto sem predo.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agent.especializados Com. p/grosso prod.', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Agentes do Comercio p/grosso imobiliario', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso cereais,alimentos p/animais', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso flores e plantas', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com. p/grosso anim. vivos, peles e couro', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso tabaco em bruto', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.por grosso frutas e prod. hortícolas', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com. p/grosso carne e prod. à base carne', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso leite e deriv,gorduras alim', 'risk' => 'Medio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso bebidas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso tabaco', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso café, açúcar,chá,cacau', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso peixe,crustáceos e moluscos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. por grosso outros prod. alimentares', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso de têxteis,vest e ca', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso têxteis, vestuário e acessó', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso calçado', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso electrod.,aparelho rád e tv', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso louça cerâm vidro,prod.limp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso perf.,prod.hig. prod.farma', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso artig.pap.,livros,revi jorn', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso out bens cons,exc alim,bebi', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso computador,exc.out.máq.escr', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso compon.equip.electr.telecom', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso máquinas e equip. agrícolas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'COMÉRCIO POR GROSSO DE OUT. MÁQUI. E EQ', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso máq., máq.p/Const.eng.civil', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso mob.escrit.,equip.escritóri', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/gros máq.equip.p/ind.,e p/out.fins', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. p/grosso comb.sól,líq gas prod deri', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso minérios e metais', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Comércio construção Canal e Climatização', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso maira em bruto e prod.rivad', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso mat Const.(excepto maira)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso ferragen,ferra.man.e aquec.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso  prod.s químicos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.p/grosso bens intermédios n/agrícola', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio por grosso, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. a retalho em supermer. e hipermer.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho outros Estab.n/esp.prod.alim', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho outros Estab.n/esp.prod.alim', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.ret.frutas prod hort.,Estab.especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho prod.base carne,em Estab.Esp', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.retalho prod.base carne,em Estab.Esp', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Com.retalho pão, prod.past.,em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.ret.frutas prod hort.,Estab.especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. a retalho bebi., em Estab. Especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. a retalho bebi., em Estab. Especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho comb p/veíc motor,Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comercio Retalh Equip TIC Est Especializ', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho computadores em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho equip telec,em Estab.espec', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.ret.frutas prod hort.,Estab.especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. a retalho têxt, em Estab. Especiali', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho ferragens,estab. Especializa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho carpetes,tape,Estab.Especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.a retalho electrod,em Estab.Especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho mob.artig.ilum,em estab.esp.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho louças,em Estab.Especializad', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.a retalh out art p/ lar,em Estab.Esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho livros, jornais,em estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho discos, CD, DVD,em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho artig desporto, em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho brinq.jogos,em Estab.especia', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comér a retlho vest Estabele especializa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.a retalho vest, em Estab. Especializ', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho marroquinaria,em Estab. Esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho prod.farmacêuticos,Estab.esp', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'OUTRO COMER RETALH PROD NOVOS ESTAB ESPE', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho artig ouriv.e joalh.Esta.Esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comretalho flores,plantas,em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho comb p/uso domé,em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho materi óptico,foto.Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho anim.estim.em Estab.esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho máq.out mat.escrit.Estab.Esp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho outro prod.nv Estab.especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho artig.seg.mão,Estab.especial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho bancas,prod.alim.beb.tabaco', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho em bancas, e similares', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho em bancas,feiras e unid móv', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com. a retalho por corresp. ou via Inter', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Com.retalho p/out.mét.,n/efect.em bancas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transp. interur pass. p/caminho de ferro', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transp. mercadorias por caminho de ferro', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transp. terr, urb e suburb, regul passag', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outros Transp.s terr não regul passag', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transportes rodoviários mercadorias', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transportes por oleodutos e gasodutos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transportes marítimos passageiros', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transportes marítimos mercadorias', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transp. passag por vias navegáveis inter', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transp. passag por vias navegáveis inter', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transportes aéreos passageiros', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Agentes do Comércio Madeira e Ferragens', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transportes aéreos mercadorias', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'COMERCIO POR GROSSO DE PRODUTOS QUIMICOS', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'COMÉRCIO POR GROSSO, N,E', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Armazenagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comer a retalho em estabel n espc c pred', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio a Retalho Est. Esp. sem Pred.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio a retalho de peixe, crust e mol', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.auxiliares dos Transp.s terrestres', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. auxiliares dos Transp.s por água', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(052220) Actividades auxiliares de transportes por água', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => 'Activ. auxiliares dos Transp.s aéreos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Manuseamento carga', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.agentes transitários,adu e activ', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio a retalho de p/. farmacêuticos', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'COMERCIA A RETALHO FERRAGEM,EQUIP SANIT', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outro comercio a reta de prdts novs esta', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => 'comercial', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas dos correios nacionais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. post inpenntes dos correios nac.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Hotéis com restaurante', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Complexos turísticos com restaurante', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Pensões com restaurante', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Estabelecimento hoteleiros, c/restaurant', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Hotéis sem restaurante', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Pensões sem restaurante', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Estab. hoteleiros sem restaurante, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Parques campismo e caravanismo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outros locais alojamento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Restaurantes tipo tradicional', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Restau. c/lugares ao balcão (snack bar)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Restaurantes sem serviço mesa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Restaurantes, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fornecimento refeições para eventos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividas serviços refeições', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cafés e pastelarias', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cervejarias e bares', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outros estabelecimentos bebidas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Edição livros', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Edição listas stinadas a consulta', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Edição jornais, rev. outras pub. Periód', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividas edição', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Edição programas informáticos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prod. filmes, vid. e programas televisão', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.Téc. pos-Prod. filmes, víd.prog tv', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Distrib filmes, víd e programas tv', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Projecção filmes e vídeos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. gravação som e edição música', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas rádio', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas televisão', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas telecomunicações por fio', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas telecomunicações sem fio', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas telecomunicações por satélite', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividas telecomunicações', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas programação informática', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas consultoria em informática', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Gestão exploração equipamento informátic', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Acti.serv.relac.c/tecno.informaçã', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.proc dados,domic. info Activ.relac', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Portais Web', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas agências notícias', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ. dos serviços informação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Banco Central', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Instituições bancárias', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outra intermediação monetária, n.e.', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Activ. socied gestoras participações soc', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Trusts, fundos e entid. financeiras simi', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => '(064201) Actividades das sociedades gestoras de participaões sociais financeiras', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],

                      ['description' => '(064202) Actividades das sociedades gestoras de participações sociais não finaceiras', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],

                      ['description' => '(064922) Actividades das sociendades financeiras para aquisição a credito', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => '(064291) Actividades das instituições financeiras de crédito', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividade locação financeira', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outras actividades crédito', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outr Activ.serv financ(exc seg fund pens', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Seg.vida outras Activ.compl.seg. social', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Seguros não vida', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Resseguros', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fundos pensões', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Administração mercados financeiros', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.neg.p/conta terceiros valores mob.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.aux.serv.fin.,exc.fund.Pens', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades avaliação do risco e danos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades mediadores seguros', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.Aux.seguros fundos pensões', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades gestão fundos', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividas imobiliárias por conta própria', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividas imobiliárias por conta  outrem', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividas jurídicas', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Activ.contab. auditoria;consultoria fisc', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],

                      ['description' => 'Auditor', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],

                      ['description' => 'Actividas das sedes sociais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(070100) Actividades das sedes sociais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.consultoria p/ negócios e a gestão', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividades arquitectura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades engenharia e técnicas afins', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades ensaios e análises técnicas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Inv.cientif desenv ciências física e nat', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Inv.científ desenv ciências soc e humana', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Publicidade', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Estudos mercado e sondagens opinião', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas Design', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas fotográficas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.consult.,científ.,técn.simi', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Actividades de Serviços e Empresa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'ACTIVIDAS VETERINÁRIAS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer veículos automóveis', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer bens recreativos e sportivos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer viocassetes e discos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer out bens uso pessoal e doméstico', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer máquinas, equipamentos agrícolas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer máq. e equip. p/Const.,eng civil', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer máq.equip.escritó(inc.computad)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer meios Transp.marítimos e fluviai', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer meios transporte aéreo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Alu.meios Transp.terr.,exc.veículos auto', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aluguer outras máquinas e equipamentos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Loca.prop.intel prod.simi,exc.direit aut', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.empresas selecção e colocação pess', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => '(078100) Actividades das empresas de selecção e colocação de pessoal', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. das empresas trabalho temporário', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => '(078200) Actividades das empresas de trabalho temporário', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outro fornecimento recursos humanos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activida das agências viagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(079110) Actividades das agências de viagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activida dos operadores turísticos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividas reservas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades Segurança Privada', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. relacionadas c/sistemas segurança', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades investigação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.combinadas apoio à gestão edifício', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(081100) Actividades combinadas de apoios aos edificios', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades limpeza geral em edifícios', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.limp.edifíci e equip.indust', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. plantação e manutenção jardins', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.combinadas serviços administrativo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Exec.fotoc.e out.Activ.espec.apoio admin', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades dos centros chamadas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Organ. feiras,cong. e outros eventos sim', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades Serviços Apoio Prest Empresa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Act. cobrança e avaliação crédito', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades embalagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.serviço apoio prest. às emp', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Administração central', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Administração regional e local', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Act. apoio à administração pública', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Administração pública - actividas saúde', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Administração pública - Activ. educação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Admi.púb-Activ.Cult.,desp.exc.seg.soc.ob', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Administração pública-Activ. económicas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Relações exteriores', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades defesa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Justiça', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividas segurança e orm pública', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades protecção civil', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Segurança social obrigatória', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino pré-escolar', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino primário', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino geral do 1º Ciclo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Formação profissional básica', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino geral do 2º Ciclo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Formação média técnica', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Formação média normal', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino superior', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino desportivo e recreativo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ensino das actividades Culturais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Escola condução e pilotagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Formação profissional', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividades educativas, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades serviços apoio à educação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. Estab. saúde com internamento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. prática méd clínica geral, em amb', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas medicina dent, e odontologia', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Laboratório análises clínicas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades enfermagem', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividades saú humana, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades enfermagem com alojamento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.Est.p/pess.c/doen.ment.toxi.c/aloj', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.acção social p/pess.idosas,c/aloj.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Acção soc. p/pessoas com def., com aloj', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.acção soc p/crianças joven, c/aloj', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.acção social,com alojamento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.acção soc p/pessoas idosas, s/aloj', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.apoio soc p/pessoas c/def,sem aloj', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.cuidados para crianças, sem aloj', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ.acção social sem alojamento', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividades de Serviços', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas das artes do espectáculo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(090010) Actividades das artes do espectáculo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividade apoio às artes do espectáculo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Criação artística e literária', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Exploração salas espec. e Activ. conexas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades das bibliotecas e arquivos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(091011) Actividades das bibliotecas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.dos museus gest.locais e mon.hist', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.jardins bot. e zoo, parq.e res.Nat', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'LOTARIAS E OUTROS JOGOS APOSTA', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outras Actividades de Serviços N.E', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Gestão instalações desportivas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades dos clubes desportivos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras actividades desportivas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Act. parques diversão e temáticos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ. diversão e recreativas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Acti.organizações económicas e patronais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades organizações profissionais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades organizações sindicais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividades organizações religiosas', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Actividades organizações políticas', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outras actividades associativas, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Rep. computador e equipamento periférico', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Reparação equipamento comunicação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Rep.tv e outros bens consumo similares', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Rep.electrod Equip.uso domést e jardim', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Reparaçã calçado e artigos couro', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Rep.mobiliário e similares uso doméstico', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Rep. relógios e artigos joalharia', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Rep. outros bens uso pessoal e doméstico', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(097000) Actividades das famílias empregadoras de pessoal doméstico', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Lavagem e limpeza a seco têxteis e peles', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ. salões cabel. e institutos beleza', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividas funerárias e conexas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Activ. serviços pessoais, n.e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.FAMÍLIAS EMPREG. PESSOAL DOMÉSTICO', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.Prod.bens pelas fam. p/uso próprio', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'ACTV.ORGAN INTERN.E OUT.INST.EXTRA-TERRI', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Comércio a Retalh. Est. Não Esp. com Pre', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Actividade Imb. Por Conta de Outrém', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'outras actividades de servicos prestados', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Particulares', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cerealicult. (excepto arroz)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Leguminosas secas e sementes oleaginosas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '1112 CULTURA DE LEGUMINOSAS SECAS E SEMENTES OLEAGINOSAS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '1120 CULTURA DE ARROZ', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],


                      ['description' => '1130 CULTURA DE HORTÍCOLAS, RAÍZES E TUBERCULOS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '1130 CULTURA DE HORTÍCOLAS, RAÍZES E TUBERCULOS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => '1160 CULTURA DE PLANTAS TEXTEIS: ALGODÃO, SISAL, JUTA, LINHO, CANHAMO, EUCALIPTO…', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => '1160 CULTURA DE PLANTAS TEXTEIS: ALGODÃO, SISAL, JUTA, LINHO, CANHAMO, EUCALIPTO', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '1130 CULTURA DE HORTÍCOLAS, RAÍZES E TUBERCULOS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '1150 CULTURA DE TABACO', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Cult. arroz', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. mandioca', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult.prod. Hortíc. out. raízes e tubérc.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. cana-açúcar', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. tabaco', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Cult. do algodão', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '1160 CULTURA DE PLANTAS TEXTEIS: ALGODÃO, SISAL, JUTA, LINHO, CANHAMO, EUCALIPTO…', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. do sisal', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Culturas plantas têxteis', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. flores e plantas ornamentais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => '1192 OUTRAS CULTURAS TEMPORÁRIAS', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => '1160 CULTURA DE PLANTAS TEXTEIS: ALGODÃO, SISAL, JUTA, LINHO, CANHAMO, EUCALIPTO…', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],

                      ['description' => 'Outras Culturas temporárias, n. e.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Viticultura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult.frutos tropicais e subtropicais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. citrinos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. pomóias e prunóias', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. outros frutos árvores e arbustos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. frutos oleaginosos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cafeicultura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outras Cult. frutos dest. à Prep. Bebida', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult.espec,plantas arom.,medici. e farma', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Outras Cultura permanentes', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Cult. materiais propagação vegetativa', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Bovinicultura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Criação gado cavalar, asinino e muar', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Criação gado ovino e caprino', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Suinicultura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Avicultura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Apicultura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Criação animais companhia', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outra produção animal, n.e', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'AgriCult. e produção animal combinadas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Caça, rep. cinegético e acti. Serv. Rel', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Activ.serv relac c/Prod.ani,exc serv vet', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prep. prod.agrícolas para a venda', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prep. e trat. sementes para propagação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'SilviCult. e outras actividas florestais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Exploração florestal', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. cortiça, resina outros prod. Flor.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Act. Serv. Rel. Silvi. Cult. Exp.flor.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Pesca marítima', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Apanha algas e outros prod.s do mar', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Pesca e apanha prod.em águas interiores', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aquacult. em águas salgadas e salobras', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Aquacult. em águas doces', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. hulha', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. lenhite', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. petróleo bruto', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Ext. gás natural', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Ext. e Prep. mineiros ferro', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Ext. minérios urânio e tório', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Ext. e Prep. minérios cobre', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Ext. e Prep. minérios metais preciosos', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Ext.Prep.minérios met.n/ferrosos', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Ext. mármore e rochas similares', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Ext. calcário, gesso e cré', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. saibro, areia e pedra britada', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. argila e caulino', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext.minerais p/indúst quím. e p/Fab.Adub', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Ext. sal', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ext. diamantes', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Ext. outros minerais não metálicos, n.e', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Activ.serv relac c/Ext.petr gás,excprosp', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Outras Activ. Serv. Relac. c/ind. Extra.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Abate gado (produção  carne)', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Abate aves e coelhos (produção  carne)', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => '(010120) Abate de Aves (Produção de carne)', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => '(010110) Abate de gado (Produção de carne)', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],

                      [
                          'description' => '1111 CEREALICULTURA (EXCEPTO ARROZ)',
                          'risk' => 'Baixo',
                          'score' => 1,
                          'indicator_id' => 10,
                      ],
                      [
                          'description' => '1112 CULTURA DE LEGUMINOSAS SECAS E SEMENTES OLEAGINOSAS',
                          'risk' => 'Baixo',
                          'score' => 1,
                          'indicator_id' => 10,
                      ],
                      [
                          'description' => '1120 CULTURA DE ARROZ',
                          'risk' => 'Baixo',
                          'score' => 1,
                          'indicator_id' => 10,
                      ],


                      ['description' => 'Fab. prod.s à base carne', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Prep. prod.s da pesca e da aquaCult.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Congelação prod. da pesca e da aquaCult.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Conserv.prod.pesca eaquacu.outros molhos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Sec.,salgas,activ.transf.prod pesca aqua', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. sumos frutos e prod.s hortícolas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Congelação frutos e prod. hortícolas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. doces, compotas, geleias marmelada', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Seca. sidratação frutos prod. hortícolas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prep. e conservação batatas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Outra Prep. conserv. frutos prod. Hort.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prod. refinação óleos gorduras vegetais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prod. refinação óleos gorduras animais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. margarinas gorduras alimentares', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Indústria do leite e rivados', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. gelados e sorvetes', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Moagem cereais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Desscasque, branq. e out. trat. do arroz', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Transformação cereais e leguminosas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. amidos,féculas e prod. afins', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Panificação', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Pastelaria', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.bolachas,biscoitos,tostas,pastelaria', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Indústria do açúcar', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ind. cacau, chocolate prod. confeitaria', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. massas alimentícias, cuscuz', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. refeições e pratos pré-cozinhados', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Refinação do sal', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Indústria do café e do chá', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. outros prod.alimentares diversos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. alimentos para animais', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. bebidas alcoólicas stiladas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prod. Vinho, bebidas fermentadas frutos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. cerveja e malte', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Eng. águas minerais naturais nascente', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. Refrig. bebidas não alcoólicas', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'INDÚSTRIA DO TABACO', 'risk' => 'Médio', 'score' => 2, 'indicator_id' => 10],
                      ['description' => 'Prep.,fia.e tec.algodão,fib.sintét.mista', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. linhas costura', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Prep.,fiação,tecel.acab. out.fibras têxt', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Acabamento têxteis', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.artig. Têxt. confecion., excep.vest.', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. tapetes e carpetes', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. cordoaria e res', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. rendas e bordados', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. outros artigos têxteis diversos', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => '(013303) Acabamento de fios, tecidos e artigos texteis não especificado', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Conf. vestuário  trabalho e  uniformes', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Conf. outro vestuário exterior em série', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Conf. outro vestuário exterior p/medida', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Conf. outro artigos acessórios vestuário', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. artigos peles com pêlo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. artigos malha', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Curtimenta acab. peles, sem e com pêlo', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.art.viag uso pessoal, marroq,correei', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Indústria do calçado e seus componentes', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Serração aplainamento impregnação maira', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.folheados,partículas,fib.out.painéis', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. obras carpintaria p/construção', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. embalagens maira', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Ind. cortiça e outras obras maira', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.pasta, papel e cartão (exc. Canel.)', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.papel cartão canel.,emb.papel e cart', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.artig. papel p/uso doméstico e sanit', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab.artigos pasta papel, papel e cartão', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Impressão', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Serviços relacionados com a impressão', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Reprodução suportes gravados', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. prod. coqueria', 'risk' => 'Baixo', 'score' => 1, 'indicator_id' => 10],
                      ['description' => 'Fab. prod. Petrolíf. Refin. Aglom. comb', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. gases industriais', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. álcool etílico fermentação', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. outros prod. químicos base', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. adubos e compostos azotados', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab.mat.Plást.borracha sint.s/forma prim', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab. pesticida outros prod. agroquímico', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],
                      ['description' => 'Fab.tintas,verniz prod.sim;tinta impress', 'risk' => 'Alto', 'score' => 3, 'indicator_id' => 10],

        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorIndicatorType::where('description', $value['description'])->exists()) {
                IndicatorIndicatorType::create($value);
            }
        }
    }
}
