pipelines:
  default:
    - step:
        name: Build and Deploy Laravel
        image: php:7.4-cli
        caches:
          - composer
          - vendorl
        script:
          # Instalar dependências do sistema
          - apt-get update && apt-get install -y libzip-dev unzip git libpng-dev libjpeg-dev libfreetype6-dev

          # Instalar Composer
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

          # Verificar a versão do Composer
          - composer --version
          

          # Atualizar o repositório com a branch principal
          - git fetch origin
          - git reset --hard origin/main

          # Instalar dependências do Composer
          - composer install --no-dev --optimize-autoloader --prefer-dist
          - vendor/bin/phpcs app/ # Corrigido o caminho para o `phpcs`

      