<?php

namespace Database\Seeders\Global;


use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class GlobalChannelSeed extends Seeder
{
    public function run()
    {
        /**IndicatorType */
        $IndicatorType = [

            //start canal
            ['description' => 'A Eternidade - Mediação de Seguros, Lda', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Benguela', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Benguela - CFB', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Huambo - Caála', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Huambo - Agência Huambo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - 1º Bairro Fiscal', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - 4 de Fevereiro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Alvalade', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Assembleia Nacional', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Atlântico', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Bºsede', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Calemba 2', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Gpl/Arredores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Hoji Ya Henda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Kapolo II', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Katyavala', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Km 30', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Maculusso', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Maianga', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Mártires', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Nosso Centro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Samba', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - São Paulo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Luanda - Vila Alice', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Lubango', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Lubango - Millenium', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Namibe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Ndalatando - Bué', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Ondjiva', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BCI - Sumbe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência - Benguela', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Aeroporto', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Agência Sede Gika', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Belo Horizonte 540', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Benguela', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Cabinda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Cacuaco', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Camama Ispeka', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Camama Multicenter', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Cimangola', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Cuca', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Huambo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Kilamba Kiaxi', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Lobito', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Lobito Restinga', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Lobito Secil', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Luanda Shopping', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Lubango', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Lubango Alfandega', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Lubango SME', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Maculusso', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Malange', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Marginal', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Menongue', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Metodista', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Namibe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Nocal', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Nocebo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Nova Vida', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Patriota', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Porto Amboim', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Porto de Luanda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Porto Seco - Viana', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Private Banking', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Rainha Ginga', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Retail Park', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Santa Clara', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Saurimo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Serviços Centrais - Gika', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Sonangalp Km32', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Sonils 541', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Sovinhos (Viana)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Soyo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Sumbe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Talatona 2', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Viana Cometa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Waco Kungo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência BK - Zé Pirão', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Avals (SU) Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Emoções e Sonhos Turism', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Express Time Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Itrios Viagens e Turism', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Jetur Viagens Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Lorm Viagens e Turismo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Machel Kiavela Mahele', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Megatours Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Nubri Viagens e Turismo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Realiza Ec Turismo, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Seetravel Viag. E Turism', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Ta Turismo Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Travelgest Turismo Gest', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Agência de Viagens - Va Service, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'AGILPREST LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Aiba-Allied Insurance Brokers Angola', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Aisim-Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Alfacenter - Corretora de Seguros Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Ana Jandira Ferreira Hely', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Angoinsurance', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Angorisk - Corretores de Seguros, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Antonio J.H. Saraiva dos Santos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Artemisia - Mediação e Corretagem de Seguros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Assiakoley Edoe Gagnom Mensah', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Babilum - Mediação de Seguros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Baltazar de Oliveira Domingos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Keve SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Keve, S.A.', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Cidade da China (506)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Huambo (1201)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Huambo “Avó Nayombo” (1202)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Lobito (1402)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Lubango (1501)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Menongue (1801)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Saurimo (801)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Agência Sede (501)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Centro de Atendimento Privado – 0504', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - Centro de Empresas Menongue (1802)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - CIP Sede (502)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu - CIP Talatona (503)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu – Colaboradores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Banco Yetu, S.A.', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Benigno Seguros - Mediação de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'BEST CHOICE - MEDIADORA DE SEGUROS LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Best Premium', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'BIG RISKS - Corretora de seguros Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Bil Klinton Kiteculo Macumbi', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'BK – CENTRO PRIME TALATONA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'BK – Colaboradores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Bk - Comercio e Serviços', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Bk - Distribuição e Logística', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Bk - Energia Gás & Petróleo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Bk – Institucional', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Bk - Minas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'BK - Produção e Industria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'BK- GDC Protocolos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Carlos Manuel Gongo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Changebiz-Mediação de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Claudio Januario Artur Antonio', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Corina Ginga Luciano Cassinda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Correspondente Bancario Yetu', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Cosea - Corretora de Seguros de Angola Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Cpseguros Angola-Corretores de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Crucial - Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'D.E.S.M Serviços(SU), Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Danilson Mauro da Silva Santos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Dickson Manuel Fernando F. Muehombo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Dinamizador – Denilson Manuel', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Dinamizador – Martinho Agostinho', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Duboys André Fançony', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'EC - MEDIAÇÃO DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'EDGAR GASPAR DOS SANTOS', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Edson Carlos Kachivela', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Egsa-Corretores de Seguros de Angola S.A', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'EL CORRETORA - CORRETORA DE SEGUROS LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Elsa Fernanda Vaz Oliveira', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'ESTABILIDADE - CORRECTORA DE SEGUROS S.AS', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Evandro Adelio Mateus dos Passos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Exu-Mediadores de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Fernando Manuel Domingos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Ferplas, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Fula Domingos Cassua Gonga', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Futuris Brokers- Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Gersist-Mediadora de Seguros Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Gidson Joao da Costa Francisco', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Global - Cartão Jovem Angola', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Global GPS', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Goo - Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Governa Seguros - Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Grupo C.A. Bilhastre, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'GUEYAN GRIND-CORRECTORA DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'H&N – Sociedade de Mediação de Seguros, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Hadiscoton Carlos Augusto', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Herlander de Jesus Andrade Silvestre', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Hong Kong Kai Xun Internacional Angola Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Huafeng.Construção Civil e Engenharia, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'ICOMAT-MEDIAÇÃO DE SEGUROS.(SU), LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'ILIDIO JOAO ANTONIO SEBASTIAO', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Ilunga Bella Miranda Junqueira', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Impelir - Mediação de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'INTER RISK ANGOLA-CORRETORA DE SEGUROS, S.A', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Interrisk - Auto Sueco', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Interseguros-Corretores de Seguros, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Joao Carlos de Sousa Meireles', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Joice Edivanio Monteiro da Silveira', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Jorge Rafael Magalhães Sarr', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'JOSE CARLOS DA ROCHA TAVARES', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Jose Luis Oleiro Morais Alçada', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Jose Miguel Paixao Pascoal', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Julio Francisco Alexandre', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Juridson Fortes Dulo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'KARLA ELAYNE DOS SANTOS LUMBOMBO EVARISTO', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Kenguele Jorge', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Korretseg - Correctora de Seguros (SU) S.A', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'LEVERAGE CONTACT CENTER, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Lider Ag - Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'LM BEST- Corrector De Seguros e de Resseguros, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Lucio Salgado da Costa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'LUDIPRE Corretora de Seguros, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'LUIS LAERCIO CORREIA DE SOUSA MALAQUIAS', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Luis Paulo Gomes Nobre', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Luisa Da Conceição Peixoto Guimarães Rufino', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Manuel Bernardo Afonso', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Manuel Cândido Antonio', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Maria de Fátima Conceição Pereira M.Sousa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'MARIA ISABEL BIMBI', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'MDS Insurance - Corretora de Seguros e de Resseguros SA - 002', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'MDS Insurance - Corretora de Seguros e de Resseguros SA - 001', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'MOISÉS NUNES CARDOSO', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Monte Car Service, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Montlour Seguros-Mediação e Corretagem, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Morpheu\'S - Mediação de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Moseg-Corretores Seguros e Resseguros, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Motorwil, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Mukuata, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Nacional Brokers Angola, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Negócio Directo Bancassurance & Protocolos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Nicolau Antonio Gomes Cabangage', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Nicole Patrícia Quimba Simão', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Nuno Miguel da Cunha Ribeiro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Olimpio Jorge Manuel', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'OPEN.S - MEDIAÇAO DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'PAULO ALEXANDRE DA CONCEIÇAO NOGUEIRA BRANCO', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Paulo Giuseppe Monteiro Berardinelli', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Paulo Sérgio Peixoto Fernandes Mendes Faria - Mediador de Seguros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Ponto Seguros-Prestação de Serviços (SU) Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Porto Seguro-Corretores e Consul. Resseg. SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Premium-Broker-Correct. Segur. Resseg. S.A.', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Proagil - Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção - Corporate', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção - Cosseguro Global', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Co-Seguro Regime Especial', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Atrium Nova Vida', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Benguela', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa – Gamek', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Huambo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Ingombota', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Lubango', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Posto Móvel Cacuaco', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Posto Móvel Fortaleza', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Sede', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Serpa Pinto', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Sumbe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Produção Directa - Talatona', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Proseff Executive, Corretora de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'REAL RISK- CORRETORES DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'RI & A - Corretores de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'RISK - TECH-CORRETOR DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Robert Hudson', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Rocket Brokers - Corretagem de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'SAFEPREMIUM - MEDIADORA DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'SAPERE AUDE- CORRETORA DE SEGUROS', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Sebastião João Morais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Segurcontas, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'SEGURÍSSIMOS - MEDIAÇÃO DE SEGUROS LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Sérgia Karinne Carlos Pereira', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'SHIELD SEGUROS - MEDIAÇAO E CORRETAGEM DE SEGUROS, LDA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'SHIMBA INSURANCE BROKER, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'SOLAR VALORIZZA CORRECTORA DE SEGUROS E RESSEGUROS, LDA.', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Solida - Mediação de Seguros, Lda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Sonangol Shipping Angola (Luanda), Lda.', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Stelvio Ataide Henriques', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Tanislau Antunes Sanuca', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Tiago dos Santos Cambiji', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Tmj', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Transeguros - Corretora, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Transversal Brokers – Corretora e Mediação de Seguros, SA', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Wilton Ivandro Franco de Oliveira', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Zacarias Raul Kituxi Panguila', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Zillian Angola – Corretores de Seguros, Limitada', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
            ['description' => 'Zizela Ruth da Costa João', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 11],
        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorType::where('description', $value['description'])->exists()) {
                IndicatorType::create($value);
            }
        }
    }
}
