<?php

namespace App\Enum;

enum TypeIndicator: int
{
    case CAPACIDADE_IDENTIFICACAO_VERIFICACAO = 1;
    case FORMA_ESTABELECIMENTO_RELACAO_NEGOCIO = 2;
    case FORMA_JURIDICA_ENTIDADE = 3;
    case RESIDENCIA = 4;
    case TIPO_ACTIVIDADE_PRINCIPAL = 5;
    case ENTIDADE_CONSIDERADA_PPE = 6;
    case TIPO_SEGURO = 7;
    case RISCO_PRODUTOS_SERVICOS_TRANSACOES_3 = 8;
    case RISCO_PRODUTOS_SERVICOS_TRANSACOES_4 = 9;
    case TIPO_ACTIVIDADE_PRINCIPAL_COLECTIVA = 10;
    case CANAIS = 11;
    case CAE = 12;
}
