<?php

namespace Database\Seeders;

use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class CountriesSeed extends Seeder
{
    public function run()
    {
           /**IndicatorType */
           $IndicatorType = [


            /**Risco Pais / País de Registo da entidade*/
            ['description' => 'Afeganistão', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'África do Sul', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Africa do Sul', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'South Africa', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Albânia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Algeria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Alemanha', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Andorra', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Angola', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Botswana', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Albania', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'American Samoa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Antarctica', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Australia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Austria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Azerbaijan', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Bahamas', 'risk' => 'Baixo', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Belarus', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            //
            ['description' => 'belgium', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Belize', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Benin', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'bermuda', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bermudas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bhutan', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Bolivia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bosnia and Herzegovina', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bouvet Island', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'British Antarctic  Territory', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'British Indian Ocean Territory', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'British Virgin Island', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Bulgaria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Cambodia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Cameroon', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Canada', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Anguila', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Austrália', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Antígua e Barbuda', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Netherlands Antilles', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Antilhas Holandesas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Áustria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Bélgica', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Bulgária', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Canadá', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Aruba', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Dinamarca', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Eslovénia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Azerbeijão', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],

            ['description' => 'Bahrain', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bangladesh', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Barbados', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Espanha', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Spain', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Estónia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],



            ['description' => 'Brasil', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],

            ['description' => 'Brazil', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],


            ['description' => 'Brunei Darussalam', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Brunei', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Burkina Faso', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Burundi', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Bielorússia ( Belarus)', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bolívia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bosnia-Herzegovina', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Bouvet, Ilha', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Finlândia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Butão', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],

            ['description' => 'Caimans, Ilhas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Camarões', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Cambodja', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'França', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'France', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Gronelândia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Centro-Africana, República', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Hungria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Hungary', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Chile', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'China, República Popular', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Chipre', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Cocos(Keeling), Ilha dos', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Cocos [Keeling] Islands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Colômbia', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Colombia', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Comores', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Comoros', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Cook,Ilhas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Cook Islands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Coreia, Rep.Pop.Democr. (Norte)', 'risk' => 'Inaceitável', 'score' => 150, 'fk_indicator' => 9],
            ['description' => 'Coreia, República (Sul)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Costa do Marfim', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Costa Rica', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Croácia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Croatia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Irlanda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Ireland', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Islândia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Iceland', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Djibouti', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Dominica', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Dominicana,República', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Egipto', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Egypt', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],

            ['description' => 'El Salvador', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Emiratos Arábes Unidos', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Equador', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Eritrea', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Itália', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Italy', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Letónia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            // Dados anteriores omitidos
            ['description' => 'Estados Unidos da América', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Lituânia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Lithuania', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Norway', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Etiópia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Noruega', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Feroe, Ilhas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Fidji', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Filipinas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Philippines', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Nova Zelândia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'New Zealand', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'New Caledonia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Polónia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Gabão', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Gambia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Gana', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Georgia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Gibraltar', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Granada', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Portugal', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'República Checa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guadalupe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guam', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Guatemala', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Guiana', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Guyana', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'French Guiana', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Slovakia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'República Eslováquia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guiné Bissau', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Guinea-Bissau', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'China', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Roménia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guiné, República da', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Haiti', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'haiti', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Suécia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Holanda', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Honduras', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Hong Kong SAR China', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Antártica', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Ilhas Marianas Setentrionais', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Ilhas Marshall', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Marshal Islands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Ilhas Mayotte', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Ilhas Menores Distantes dos Est.Uni.Amer', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'India', 'risk' => 'Alto', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Indonésia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Indonesia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Irão, República Islâmica do', 'risk' => 'Inaceitável', 'score' => 150, 'fk_indicator' => 9],
            ['description' => 'Iraque', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Iraq', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Arábia Saudita', 'risk' => 'Baixo', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Argélia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Argentina', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Armenia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Jamaica', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Jordania', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Jordan', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Kiribati', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Kuwait', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Laos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Casaquistão', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Chade', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Chad', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],

            ['description' => 'Libano', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Libéria', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Liberia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Libia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Liechtenstein', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Cuba', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Luxemburgo', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Luxembourg', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Macau', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Grécia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guiana Francesa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Malásia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Malaysia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Guiné Equatorial', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Equatorial Guinea', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Guinea', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Maldivas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Mali', 'risk' => 'Alto', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Malta', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Marrocos', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Morocco', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Heard e McDonald, Ilhas', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'heard Island and McDonald Islands', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Mauricia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Israel', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'México', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Mianmar', 'risk' => 'Inaceitável', 'score' => 150, 'fk_indicator' => 9],
            ['description' => 'Myanmar [Burma]', 'risk' => 'Inaceitável', 'score' => 150, 'fk_indicator' => 9],
            ['description' => 'Moçambique', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Mozambique', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Moldavia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Mónaco', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Mongólia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Mongolia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Montserrat', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Japão', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Japan', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Lesoto', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Lesotho', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Nauru', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Macedonia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Nicarágua', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Niger', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Nigéria', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Nigeria', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Niue', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Norfolk, Ilha', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Madagascar', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Nova Caledónia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Malawi', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Martinica', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Oman', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Palau', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Palestina', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Panama Canal Zone', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Panama', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Papuásia Nova Guiné', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Mauritania', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Paraguai', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Peru', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Pitcairn,Ilha', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Polinésia Francesa', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Namíbia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Namibia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Porto Rico', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Puerto Rico', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Nepal', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Qatar', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Oceano Indico.Ter.Brit.do', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Quénia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Reino Unido', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Quirguistão', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Kyrgyzstan', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Republica Democratica do Congo', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Congo - Brazzaville', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Congo - Kinshasa', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Paraguay', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'República do Yemen', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Yemen', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Ruanda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Rwanda', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Reunião', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Réunion', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Saara Ocidental', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Serra Leoa', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Sierra Leone', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Russia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Sri Lanka', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Salomão,Ilhas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Solomon Islands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Samoa', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Samoa Americana', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Santa Helena', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Sain Helena', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Santa Lucia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Cristovão e Névis', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Sainr Kitts and Nevis', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'São Marinho', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Pedro e Micuelon', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Tomé e Principe', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'São Vicente e Granadinas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Sain Vicente and the Grenadines', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Senegal', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Suriname', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'SERVIA', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Seychelles', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Singapura', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],


            ['description' => 'Siria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Somália', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Zâmbia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Sudão', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Sudan', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Falklands, Ilhas (Malvinas)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Suiça', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Natal, Ilha', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Svalbard e Ilha Mayen', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Tailandia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Taiwan (Formosa)', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Taiwan', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Tajikistan', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Tajiquistão', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Tanzania', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],

            ['description' => 'Terras Austrais e Antarticas Francesas', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Timor-Lest', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Timor Leste', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Togo', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Tokelau', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Tonga', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Trinidade e Tobago', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Trindan and Tobaco', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Tunisia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Turcas e Caiques,Ilhas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Turks and Caicos Islands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Turquemenistão', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Turkmenistan', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Turquia', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Turkey', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Tuvalu', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Ucrania', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Uganda', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Paquistão', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Pakistan', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Uzbequistão', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Vanuatu', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Vaticano', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Venezuela', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Vietname', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Virgens Americanas,Ilhas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Virgens Britanicas,Ilhas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Wallis e futuna,Ilhas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Uruguai', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Zimbabwe', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Zona Neutra, Arábia Saudita /Iraque', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],


            /**end países */
            ['description' => 'Neutral Zone', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'cape verde', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Cayman Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Central African Replubic', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Christmas Island', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Cyprus', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Czech Republic', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => "Còte D'Ivoire", 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Denmark', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Dominican Republic', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Dronning Maud Land', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'East Germany', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Germany', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Ecuador', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Estonia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Ethiopia', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Falkaland Islandas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Faroe Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Fiji', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Finland', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'French Polynesia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'French Southern Territories', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'French Southern Antarctic Territories', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Gabon', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Ghana', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Greece', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Greenland', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Grenada', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guadeloupe', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Guemsey', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Iran', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'isle of Man', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Jersey', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Ilha Johnston', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Kazakhstan', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Kenya', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Latvia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Lebanon', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Libya', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Maurício', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Mauritius', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Metropolitan France', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'França Metropolitana', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Mexico', 'risk' => 'Mexico', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Micronésia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Micronesia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Ilhas Midway', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Midway Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Moldova', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Monaco', 'risk' => 'Monaco', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Montenegro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Netherlands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Nicaragua', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Ilha Norfolk', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Coreia do Norte', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'North Korea', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Vietnã do Norte', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'North Vietnam', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Northerm Mariana Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Osman', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Palestinian Territories', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Papua New Guinea', 'risk' => 'Medio', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'People Democratic Republic of Yemen', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Pitcaim islands', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Polônia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Poland', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Romênia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Romania', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Bartolomeu', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Saint Berthélemy', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Santa Lúcia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Saint Lucia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Martinho', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Saint Martin', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Pedro e Miquelon', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Saint Pierre and Miquelon', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'San Marino', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],


            ['description' => 'Serbia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Sérvia e Montenegro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

            ['description' => 'Eslovênia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Slovenia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Somalia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Geórgia do Sul e Ilhas Sandwich do Sul', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'South Korea', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Coreia do Sul', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Suíça', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Switzerland', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Síria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Syria', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'São Tomé and Principe', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'U.S Minor Outlying Pacific Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'U.S Virgin Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Union of Sovietic Socialist Republics ', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'United Kingdom', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'United States', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Unknown or Invalid Region', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Uruguay Uzbekistan', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Vatican City', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Venezuea', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 9],
            ['description' => 'Vietnam', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 9],
            ['description' => 'Wake Island', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Wallis and Futuna', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Westrn Sahara', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Zambia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],
            ['description' => 'Aland Islands', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 9],

   ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorType::where('description', $value['description'])->exists()) {
                IndicatorType::create($value);
            }
        }

    }

}
