<?php

namespace Database\Seeders;

use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class InsuranceTypeSeed extends Seeder
{
    public function run()
    {
        /**IndicatorType */
        $IndicatorType = [

            /**Tipo de Seguro */

            ['description' => 'Automóvel Frota', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],

            ['description' => 'Assistência Viagem', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'A.P. - Desporto', 'risk' => 'Baixo', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'Automóvel Individual', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Automóvel Frota', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],

            ['description' => 'seguro de Propriedade Comercial A.P. - Desporto', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Comercial A.P. - Escolar', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'Seguro de Saúde e Lesões A.P. - Grupo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro de Saúde e Lesões A.P. - Individual', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro de Saúde e Lesões A.P. - Prestígio', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'AT - Conta de Outrem', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'AT - Prémio Fixo', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'Seguro Automóvel Automóvel Frota', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro Automóvel Automóvel Individual', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro de Aviação Aviação', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 8],
            ['description' => 'Seguro de Maritimo de Casco e Máquina Casco', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 8],
            ['description' => 'Seguros Maritimos Embarcações de Recreio', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Comercial Máquinas Cascos', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Condomínio Multi Riscos Condominio', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Comercial Multi Riscos Empresa', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de propriedade Residencial Multi Riscos Habitação', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Comercial Multi Riscos Indústria', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de propriedade Residencial Multirriscos Habitação', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'Seguro de Saúde e Lesões Protecção à Família', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Comercial R.C. - Exploração', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'seguro de Propriedade Comercial R.C. - Geral', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => 'Seguro de Saúde e Lesões R.C. - Profissional', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro de Saúde e Lesões Saúde AdvanceCare', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro de Automóveis T. M. - Rodoviário', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 8],
            ['description' => 'Seguro de Vida Vida Crédito Individual', 'risk' => 'Muito Alto', 'score' => 20, 'fk_indicator' => 8],
            ['description' => '1121 SEGURO DE AGRICULTURA (AVENÇA)', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 8],
            ['description' => '1122 SEGURO DE AGRICULTURA (GENÉRICO)', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 8],

            [
                'description' => '1121 SEGURO DE AGRICULTURA (AVENÇA)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1122 SEGURO DE AGRICULTURA (GENÉRICO)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1130 CULTURA DE HORTÍCOLAS, RAÍZES E TUBÉRCULOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1140 CULTURA DE CANA-DE-AÇÚCAR',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1150 CULTURA DE TABACO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1160 CULTURA DE PLANTAS TEXTEIS: ALGODÃO, SISAL, JUTA, LINHO, CANHAMO, EUCALIPTO…',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1191 CULTURA DE FLORES E DE PLANTAS ORNAMENTAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1192 OUTRAS CULTURAS TEMPORÁRIAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1210 VITICULTURA (CULTURA DA VINHA)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1220 CULTURA DE FRUTOS TROPICAIS E SUBTROPICAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1230 CULTURA DE CITRINOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1240 CULTURA DE POMÓIDEAS E PRUNÓIDEAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1251 CULTURA DE FRUTOS DE CASCA RIJA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1252 CULTURA DE OUTROS FRUTOS EM ÁRVORES E ARBUSTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1261 OLIVICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1262 CULTURA DE OUTROS FRUTOS OLEAGINOSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1270 CULTURA DE PLANTAS DESTINADAS À PREPARAÇÃO DE BEBIDAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1280 CULTURA DE ESPECIARIAS, PLANTAS AROMÁTICAS, MEDICINAIS E FARMACÊUTICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1290 OUTRAS CULTURAS PERMANENTES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1300 CULTURA DE MATERIAIS DE PROPAGAÇÃO VEGETATIVA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1410 CRIAÇÃO DE BOVINOS PARA A PRODUÇÃO DE LEITE',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1420 CRIAÇÃO DE OUTROS BOVINOS (EXCEPTO P/PRODUÇÃO DE LEITE) E BÚFALOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1430 CRIAÇÃO DE EQUINOS, ASININOS E MUARES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1440 CRIAÇÃO DE CAMELOS E CAMELÍDEOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1450 CRIAÇÃO DE OVINOS E CAPRINOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1460 SUINICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1470 AVICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1491 APICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1492 CUNICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1493 CRIAÇÃO DE ANIMAIS DE COMPANHIA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1494 OUTRA PRODUÇÃO ANIMAL NÃO ESPECIFICADA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1500 AGRICULTURA E PRODUÇÃO ANIMAL COMBINADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1610 ACTIVIDADES RELACIONADAS COM AGRICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1620 ACTIVIDADES RELACIONADAS COM PRODUÇÃO ANIMAL EXCEPTO SERVIÇOS DE VETERINÁRIA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1630 PREPARAÇÃO DE PRODUTOS AGRÍCOLAS PARA VENDA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1640 PREPARAÇÃO E TRATAMENTO DE SEMENTES PARA PROPAGAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1701 CAÇA E REPOVOAMENTO CINEGÉTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '1702 ACTIVIDADES DOS SERVIÇOS RELACIONADAS COM CAÇA E REPOVOAMENTO CINEGÉTICO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '2100 SILVICULTURA E EXPLORAÇÃO FLORESTAL',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '2200 EXPLORAÇÃO FLORESTAL',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '2300 EXTRACÇÃO DA CORTIÇA, RESINA E APANHA DE OUTROS PRODUTOS FLORESTAIS, EXCEPTO MADEIRA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '2400 ACTIVIDADES RELACIONADAS C/SILVICULTURA E EXPLORAÇÃO FLORESTAL',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '3111 PESCA MARÍTIMA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '3112 APANHA DE ALGAS E DE OUTROS PRODUTOS DO MAR',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],

            [
                'description' => '3121 PESCA EM ÁGUAS INTERIORES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '3122 APANHA DE PRODUTOS EM ÁGUAS INTERIORES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '3210 AQUICULTURA EM ÁGUAS SALGADAS E SALOBRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '3220 AQUICULTURA EM ÁGUAS DOCES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '5100 EXTRACÇÃO DE HULHA (INCLUI ANTRACITE)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '5200 EXTRACÇÃO DE LENHITE',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '6100 EXTRACÇÃO DE PETRÓLEO BRUTO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '6200 EXTRACÇÃO DE GÁS NATURAL',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '7100 EXTRACÇÃO E PREPARAÇÃO DE MINÉRIOS DE FERRO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '7210 EXTRACÇÃO DE MINÉRIOS DE URÂNIO E DE TÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '7290 EXTRACÇÃO E PREPARAÇÃO DE OUTROS MINÉRIOS METÁLICOS NÃO FERROSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8111 EXTRACÇÃO DE MÁRMORE E OUTRAS ROCHAS CARBONATADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8112 EXTRACÇÃO DE GRANITO ORNAMENTAL E ROCHAS SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8113 EXTRACÇÃO DE CALCÁRIO E CRÉ',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8114 EXTRACÇÃO DE GESSO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8115 EXTRACÇÃO DE ARDÓSIA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8121 EXTRACÇÃO DE SAIBRO, AREIA E PEDRA BRITADA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8122 EXTRACÇÃO DE ARGILAS E CAULINO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8910 EXTRACÇÃO DE MINERAIS P/INDÚSTRIA QUÍMICA E FABRICAÇÃO ADUBOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8920 EXTRACÇÃO DA TURFA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8931 EXTRACÇÃO DE SAL MARINHO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8932 EXTRACÇÃO DE SAL GEMA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8991 EXTRACÇÃO DE FELDSPATO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '8992 EXTRACÇÃO DE OUTROS MINERAIS NÃO METÁLICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '9100 ACTIVIDADES DOS SERVIÇOS RELACIONADOS COM A EXTRACÇÃO DE PETRÓLEO E GÁS, EXCEPTO A PROSPECÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '9900 OUTRAS ACTIVIDADES DOS SERVIÇOS RELACIONADOS COM AS INDÚSTRIAS EXTRACTIVAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10110 ABATE DE GADO (PRODUÇÃO DE CARNE)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10120 ABATE DE AVES (PRODUÇÃO DE CARNE)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10130 FABRICAÇÃO DE PRODUTOS À BASE DE CARNE',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10201 PREPARAÇÃO DE PRODUTOS DA PESCA E DA AQUICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10202 CONGELAÇÃO DE PRODUTOS DA PESCA E DA AQUICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10203 CONSERVAÇÃO DE PRODUTOS DA PESCA E DA AQUICULTURA EM AZEITE E OUTROS ÓLEOS VEGETAIS E OUTROS MOLHOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10204 SALGA, SECAGEM E OUTRAS ACTIVIDADES DE TRANSFORMAÇÃO DE PRODUTOS DA PESCA E AQUICULTURA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10310 PREPARAÇÃO E CONSERVAÇÃO DE BATATAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10320 FABRICAÇÃO DE SUMOS DE FRUTOS E PRODUTOS HORTÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10391 CONGELAÇÃO DE FRUTOS E DE PRODUTOS HORTÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10392 SECAGEM E DESIDRATAÇÃO DE FRUTOS E DE PRODUTOS HORTÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10393 FABRICAÇÃO DE DOCES, COMPOTAS, GELEIAS E MARMELADA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10394 DESCASQUE E TRANSFORMAÇÃO DE FRUTOS DE CASCA RIJA COMESTÍVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10395 PREPARAÇÃO E CONSERVAÇÃO DE FRUTOS E PRODUTOS HORTÍCOLAS POR OUTROS PROCESSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10411 PRODUÇÃO DE ÓLEOS E GORDURAS ANIMAIS BRUTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10412 PRODUÇÃO DE AZEITE',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10413 PRODUÇÃO DE ÓLEOS VEGETAIS BRUTOS (EXCEPTO AZEITE)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10414 REFINAÇÃO DE AZEITE, ÓLEOS E GORDURAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '10420 FABRICAÇÃO DE MARGARINAS E DE GORDURAS ALIMENTARES SIMILARES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '21100 FABRICAÇÃO DE PRODUTOS FARMACÊUTICOS DE BASE',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '21201 FABRICAÇÃO DE MEDICAMENTOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '21202 FABRICAÇÃO DE OUTRAS PREPARAÇÕES E DE ARTIGOS FARMACEUTICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23110 FABRICAÇÃO DE VIDRO PLANO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23120 MOLDAGEM E TRANSFORMAÇÃO DE VIDRO PLANO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23131 FABRICAÇÃO DE VIDRO DE EMBALAGEM',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23132 CRISTALARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23140 FABRICAÇÃO DE FIBRAS DE VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23190 FABRICAÇÃO E TRANSFORMAÇÃO DE OUTRO VIDRO (INCLUI VIDRO TÉCNICO)',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '23200 FABRICAÇÃO DE PRODUTOS CERÂMICOS REFRACTÁRIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '25910 FABRICAÇÃO DE EMBALAGENS METÁLICAS PESADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '25920 FABRICAÇÃO DE EMBALAGENS METÁLICAS LIGEIRAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '25931 FABRICAÇÃO DE PRODUTOS DE ARAME',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '25932 FABRICAÇÃO DE MOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '25933 FABRICAÇÃO DE CORRENTES METÁLICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '25940 FABRICAÇÃO DE REBITES, PARAFUSOS E PORCAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '27110 FABRICAÇÃO DE MOTORES, GERADORES E TRANSFORMADORES ELÉCTRICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '27121 FABRICAÇÃO DE MATERIAL DE DISTRIBUIÇÃO E DE CONTROLO PARA INSTALAÇÕES ELÉCTRICAS DE ALTA TENSÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '27122 FABRICAÇÃO DE MATERIAL DE DISTRIBUIÇÃO E DE CONTROLO PARA INSTALAÇÕES ELÉCTRICAS DE BAIXA TENSÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '29100 FABRICAÇÃO DE VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '29200 FABRICAÇÃO DE CARROÇARIAS, REBOQUES E SEMI-REBOQUES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '29310 FABRICAÇÃO DE EQUIPAMENTO ELÉCTRICO E ELECTRÓNICO PARA VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '29320 FABRICAÇÃO DE OUTROS COMPONENTES E ACESSÓRIOS PARA VEÍCULOS AUTOMÓVEIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '38111 RECOLHA DE RESÍDUOS INERTES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '38112 RECOLHA DE OUTROS RESÍDUOS NÃO PERIGOSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '38120 RECOLHA DE RESÍDUOS PERIGOSOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '43210 INSTALAÇÃO ELÉCTRICA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '43221 INSTALAÇÃO DE CANALIZAÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '43222 INSTALAÇÃO DE CLIMATIZAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '43290 OUTRAS INSTALAÇÕES EM CONSTRUÇÕES',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46211 COMÉRCIO POR GROSSO DE ALIMENTOS PARA ANIMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46212 COMÉRCIO POR GROSSO DE TABACO EM BRUTO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46213 COMÉRCIO POR GROSSO DE CORTIÇA EM BRUTO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46214 COMÉRCIO POR GROSSO DE CEREAIS, SEMENTES, LEGUMINOSAS, OLEAGINOSAS E OUTRAS MATÉRIAS-PRIMAS AGRÍCOLAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46220 COMÉRCIO POR GROSSO DE FLORES E PLANTAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46230 COMÉRCIO POR GROSSO DE ANIMAIS VIVOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46240 COMÉRCIO POR GROSSO DE PELES E COURO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46421 COMÉRCIO POR GROSSO DE VESTUÁRIO E ACESSÓRIOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46422 COMÉRCIO POR GROSSO DE CALÇADO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46430 COMÉRCIO POR GROSSO DE ELECTRODOMÉSTICOS, APARELHOS DE RÁDIO E DE TELEVISÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46441 COMÉRCIO POR GROSSO DE LOUÇAS EM CERÂMICA E EM VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46442 COMÉRCIO POR GROSSO DE PRODUTOS DE LIMPEZA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46430 COMÉRCIO POR GROSSO DE ELECTRODOMÉSTICOS, APARELHOS DE RÁDIO E DE TELEVISÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46441 COMÉRCIO POR GROSSO DE LOUÇAS EM CERÂMICA E EM VIDRO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46442 COMÉRCIO POR GROSSO DE PRODUTOS DE LIMPEZA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46450 COMÉRCIO POR GROSSO DE PERFUMES E DE PRODUTOS DE HIGIENE',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46460 COMÉRCIO POR GROSSO DE PRODUTOS FARMACÊUTICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46470 COMÉRCIO POR GROSSO DE MÓVEIS PARA USO DOMÉSTICO, CARPETES, TAPETES E ARTIGOS DE ILUMINAÇÃO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46480 COMÉRCIO POR GROSSO DE RELÓGIOS E DE ARTIGOS DE OURIVESARIA E JOALHARIA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46711 COMÉRCIO POR GROSSO DE PRODUTOS PETROLÍFEROS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46712 COMÉRCIO POR GROSSO COMBUSTÍVEIS SÓLIDOS, LÍQUIDOS E GASOSOS, NÃO DERIVADOS DO PETRÓLEO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46720 COMÉRCIO POR GROSSO DE MINÉRIOS E DE METAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46731 COMÉRCIO POR GROSSO DE MADEIRA EM BRUTO E DE PRODUTOS DERIVADOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46732 COMÉRCIO POR GROSSO DE MATERIAIS DE CONSTRUÇÃO (EXCEPTO MADEIRA) E EQUIPAMENTO SANITÁRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46740 COMÉRCIO POR GROSSO DE FERRAGENS, FERRAMENTAS MANUAIS E ARTIGOS PARA CANALIZAÇÕES E AQUECIMENTO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '46750 COMÉRCIO POR GROSSO DE PRODUTOS QUÍMICOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '66210 ACTIVIDADES DE AVALIAÇÃO DE RISCOS E DANOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],

            [
                'description' => '66300 ACTIVIDADES DE GESTÃO DE FUNDOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86100 ACTIVIDADES DOS ESTABELECIMENTOS DE SAÚDE COM INTERNAMENTO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86210 ACTIVIDADES DE PRÁTICA MÉDICA DE CLÍNICA GERAL, EM AMBULATÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86220 ACTIVIDADES DE PRÁTICA MÉDICA DE CLÍNICA ESPECIALIZADA, EM AMBULATÓRIO',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86230 ACTIVIDADES DE MEDICINA DENTÁRIA E ODONTOLOGIA',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86901 LABORATÓRIOS DE ANÁLISES CLÍNICAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86902 ACTIVIDADES DE AMBULÂNCIAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86903 ACTIVIDADES DE ENFERMAGEM',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86904 CENTROS DE RECOLHA E BANCOS DE ÓRGÃOS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86905 ACTIVIDADES TERMAIS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
            [
                'description' => '86906 OUTRAS ACTIVIDADES DE SAÚDE HUMANA, NÃO ESPECIFICADAS',
                'risk' => 'Baixo',
                'score' => 1,
                'fk_indicator' => 8,
            ],
        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorType::where('description', $value['description'])->exists()) {
                IndicatorType::create($value);
            }
        }
    }
}
