<?php

namespace Database\Seeders;

use App\Models\IndicatorType;
use Illuminate\Database\Seeder;

class ProfissionPSeed extends Seeder
{
    public function run()
    {
           /**IndicatorType */
           $IndicatorType = [

            /**Profissão */
            ['description' => 'Funcionario Publico', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Professores Ensino Superior', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Arquitectos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Medicos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Dentistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Estomatologistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Odontologistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Advogados', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Consultores Juridicos', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Notarios', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Economistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Engenheiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Químicos e Físicos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Geofísicos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Meteorologistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Zoólogos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Agrônomos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Esteticistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Analistas de Sistemas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Guias Turísticas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Intérpretes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Tradutores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos de Contas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Contabilistas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Contabilista', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'contabilista', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Secretarias Direção', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Inspetores de Finanças', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Escritores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Jornalistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Repórteres Fotográficos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Criadores Artísticos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Cenógrafos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Realizadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Pivots', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Locutores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Produtores Artísticos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Sargento das Forças Armadas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Sargentos PSP', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Sargentos da GNR', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Agentes da PJ', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Regentes Agrícolas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos Agrícolas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Profissionais da Saúde', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Enfermeiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Fisioterapeuta', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Terapeutas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Radiologistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos Análises Clínicas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Parteiras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Educadores de Infância', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Assistentes Sociais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Professores Ensino Primário', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Monitores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Formadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Instrutores de Condução', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Guias Turísticos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Interpretes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],

            ['description' => 'Bibliotecários', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Arquivistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Solicitadores', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Programadores e Técnicos Informática', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos Informáticos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Electricistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Montadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos de Reparações', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Electro-Mecânicos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Desenhadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Topógrafos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Cartógrafos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Geómetras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Hidrometrístas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos de Som', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos de Imagem', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Artistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Desportistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Técnicos Especializados', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Comerciantes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Industriais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Construtores Civis', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empreiteiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Agricultores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empresários Agrícolas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes de Exploração Agrícola', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Criadores de Animais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes de Departamento', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes de Repartições', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes de Seções Administrativas', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Chefes de Vendas', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Chefes de Compras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes Estações CP', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes dos CTT', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes Outros Serviços Transp.e Com.', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados de Escritório', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Profissionais de Seguros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Secretárias', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Guarda-Livros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Contabilistas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Empregados Bancários', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados de Balcão', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Ajudantes de Farmácia', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Caixas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Comissário de Bordo', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Hospedeiras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Manequins', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Modelos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Vendedores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Delegados Informação Médica', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Delegados Comerciais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Promotores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Angariadores de Seguros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Dactilógrafos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Introdutores de Dados', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Recepcionista', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Telefonista', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Inspectores de Finanças', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Fiscais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Inspectores Outros Org. Públic', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Praças e Cabos Forças Armadas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Agentes da PSP e GNR', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Bombeiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Guardas Prisionais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Encarregados Fabris', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes de Armazém', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Capatazes Construção Civil', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Fiscais Construção Civil', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Fiscais de Mercados e Praças', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Fiscais dos Transportes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => '(052230) Actividades auxiliares de transportes aéreos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Operários Fabris', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Operários', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Operário', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Mineiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Metalúrgico', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Corticeira', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados Bancários', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados Construção Civil', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Pedreiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Pintores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Marceneiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Carpinteiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Canalizadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Alfaiates', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Costureiras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Modistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Bordadeiras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Costureiros de Peles', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Sapateiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Cabeleireiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Barbeiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],

            ['description' => 'Massagistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Mecânicos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Bate-Chapas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Pintores de Automóveis', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Motoristas de Pesados Mercadorias', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Motoristas pesados passageiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Motoristas de ligeiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Maquinistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Motoristas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Cozinheiro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Pasteleiro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Padeiro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefe de Mesa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Despenseiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Governantas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Mordomos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados de Hotel', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Encarregados de refeitórios', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Electricistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Montadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Desenhadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Técnicos Reparação Electro-Mecânica', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Trabalhadores Artes Gráficas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Heliógrafos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Litógrafos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Trabalhadores Artes Gráficas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Nadadores-Salvadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Mergulhadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Maqueiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Socorristas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Banheiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Artistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Desportistas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Monitores Cursos Profissionais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Formadores Cursos Profissionais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Trabalhadores Qualificados', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Trabalhadores Especializados', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Trabalhadores Rurais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Jardineiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Pescadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Tratadores de Animais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Trabalhadores Florestais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Caçadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Trolhas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados de Limpeza/Mesa/Armazém', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Abastecedor de Combustível', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Ajudante de Cozinha', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Ajudante de Motorista', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Coveiro', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Cantoneiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Estivadores/Carregadores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Engomadeiras', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Lavadeiras/Pastores/Engraxador', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Outros Ajudantes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Auxiliares Ação Médica', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Auxiliares Ação Educativa', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Continuos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Vigilantes Infantis', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Assistentes de Consultórios', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Auxiliares Administrativos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => '(082110) Actividades combinadas de serviços administrativos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Estagiários', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Porteiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Carteiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Cobradores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Paquetes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Seguranças', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Guardas-Nocturnos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Guardas Florestais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Fotógrafos (s/ curso profissional)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Vendedores Ambulantes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Caixeiros Viajantes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Feirantes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Ardinas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Vendedores de Jornais', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Peixeiros', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empregados de Quiosques', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Donos de Quiosques', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Floristas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Desempregados', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Reformados', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Pensionistas', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Aposentados', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'A Viver de Rendimentos', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Domestica', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Estudante', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Governador', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Governadora', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => "Embaixador", "comment" => "", "risk" => "Alto", "score" => "3", "fk_indicator" => 5],
            ['description' => 'Domestico', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Auditor', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Comercial', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Deputados', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Ministros', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Presidente da Câmara', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Diplomatas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Juizes', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Secretarios de Estado', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Direct. Gerais Admin. Publica', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Chefes Divisao Adm. Publica', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Administradores de Empresas', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Administradora Municipal Viana', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Administradora Municipal Luanda', 'risk' => 'Medio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Directores', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Proprietarios de Empresas', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Empresarios', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Gestores', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Gerentes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Socios Gerentes', 'risk' => 'Médio', 'score' => 2, 'fk_indicator' => 5],
            ['description' => 'Construtores Civis (>10 ano)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empreiteiros (>10 ano)', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Gerentes Bancarios', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Bancarios', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Bancários', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Empresarios Agricolas', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Chefes Explor. Agricola (>10§', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Oficiais Superiores da Armada', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Oficiais Superiores PSP', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Oficiais Superiores GNR', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Comandantes de Avioes', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Comandantes da Marinha', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Comandantes da Forca Area', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Comandantes Marinha Mercante', 'risk' => 'Alto', 'score' => 3, 'fk_indicator' => 5],
            ['description' => 'Pilotos', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],
            ['description' => 'Inspectores Sanitarios', 'risk' => 'Baixo', 'score' => 1, 'fk_indicator' => 5],


        ];

        //inserindo os indicadores
        foreach ($IndicatorType as $value) {
            if (!IndicatorType::where('description', $value['description'])->exists()) {
                IndicatorType::create($value);
            }
        }

    }
}
